CREATE TABLE securities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    isin VARCHAR(12),
    name VARCHAR(255) NOT NULL,
    asset_type VARCHAR(20) NOT NULL,
    trading_currency VARCHAR(3) NOT NULL,
    country_code VARCHAR(2),
    sector VARCHAR(100),
    coupon_rate NUMERIC(19, 4),
    maturity_date DATE
);

CREATE UNIQUE INDEX idx_securities_symbol ON securities (symbol);

CREATE TABLE positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts (id),
    security_id BIGINT NOT NULL REFERENCES securities (id),
    total_quantity NUMERIC(19, 4) NOT NULL,
    average_purchase_price NUMERIC(19, 4) NOT NULL
);

CREATE INDEX idx_positions_account_id ON positions (account_id);
CREATE INDEX idx_positions_security_id ON positions (security_id);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts (id),
    security_id BIGINT NOT NULL REFERENCES securities (id),
    transaction_type VARCHAR(20) NOT NULL,
    quantity NUMERIC(19, 4),
    price NUMERIC(19, 4),
    fee NUMERIC(19, 4),
    tax NUMERIC(19, 4),
    split_ratio NUMERIC(19, 4),
    transaction_currency VARCHAR(3) NOT NULL,
    fx_rate_to_portfolio NUMERIC(19, 6),
    transaction_date DATE NOT NULL
);

CREATE INDEX idx_transactions_account_id ON transactions (account_id);
CREATE INDEX idx_transactions_security_id ON transactions (security_id);

CREATE TABLE fx_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_currency VARCHAR(3) NOT NULL,
    quote_currency VARCHAR(3) NOT NULL,
    rate_date DATE NOT NULL,
    rate NUMERIC(19, 6) NOT NULL
);

CREATE INDEX idx_fx_rates_lookup ON fx_rates (base_currency, quote_currency, rate_date);
