-- Refresh-Token, damit ein Seiten-Reload nicht abmeldet (SEC-1/SEC-2 bleiben gewahrt: das
-- Zugriffs-Token liegt weiterhin nur im Speicher des Browsers, der Refresh-Token in einem
-- httpOnly-Cookie und ist damit für JavaScript unlesbar).
--
-- Gespeichert wird nur der SHA-256-Hash, nie der Token selbst: wer die Tabelle liest, hält damit
-- keine benutzbaren Tokens in der Hand. Dieselbe Überlegung wie bei password_hash in V1.
--
-- revoked_at statt DELETE, weil eine rotierte Kette nachvollziehbar bleiben soll: bei jedem
-- Refresh wird der alte Token entwertet und ein neuer ausgegeben.
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);
